version: '3'
services:
  web:
    image: nginx:alpine
    ports:
      - "8081:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
      - ./netbox.webp:/usr/share/nginx/html/netbox.webp
